/*******************************************************************************
 *
 * realevol - Real time evolution solver based on TRIQS
 *
 * Copyright (C) 2014-2020, I. Krivenko, M. Danilov, P. Kubiczek
 *
 * realevol is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * realevol is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * realevol. If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
#include <triqs/utility/first_include.hpp>

#include <csignal>

#include <triqs/utility/signal_handler.hpp>

#include "mesh_utils.hpp"
#include "hs_structure.hpp"
#include "compute.hpp"

namespace signal_handler = triqs::signal_handler;

static void check_signals() {
 if(signal_handler::received()) {
  int signal = signal_handler::last();
  if(signal == SIGINT) TRIQS_KEYBOARD_INTERRUPT;
  else                 TRIQS_RUNTIME_ERROR;
 }
}

namespace realevol {

template<std::size_t NPoints, typename HamiltonianType>
time_container_t<NPoints> compute_impl(std::array<static_operator_t, NPoints> const& ops,
                                       init_state const& initial_state,
                                       HamiltonianType const& h_,
                                       mesh_t_t const& t_mesh,
                                       solver_parameters_t const& params,
                                       mpi::communicator const& comm) {
  // Complete fundamental operator set of the problem
  auto const& fops = initial_state.get_fops();

  auto check_fops_subset = [&fops](fundamental_operator_set const& subfops,
                                   auto const& op,
                                   std::string const& op_name) {
    for(statistic_enum stat : {Fermion, Boson}) {
      for(auto it = subfops.begin(stat); it != subfops.end(stat); ++it) {
        if(!fops.has_indices(it->index, stat))
          TRIQS_RUNTIME_ERROR << op_name << " = " << op
                              << " contains a "
                              << (stat == Fermion ? "fermionic" : "bosonic")
                              << " index "
                              << it->index
                              << " incompatible with the initial problem";
      }
    }
  };

  signal_handler::start();

  // Check fundamental operator set generated by the Hamiltonian
  auto h_fops = h_.make_fundamental_operator_set();
  check_fops_subset(h_fops, h_, "Hamiltonian H");

  // Scan for the coefficients constant at all points of t_mesh,
  // and replace them with the corresponding constants
  auto h = try_reduce_to_constant(h_, t_mesh);

  if(params.verbosity >= 2)
    std::cout << "The Hamiltonian of the problem:" << std::endl
              << h << std::endl;

  // Fundamental operator sets generated by 'ops'
  auto ops_fops = map_array([](auto const& op) {
    return op.make_fundamental_operator_set();
  }, ops);

  // Fundamental operator set generated by all elements of 'ops' together
  fundamental_operator_set all_ops_fops;
  for(std::size_t n = 0; n < ops_fops.size(); ++n) {
    check_fops_subset(ops_fops[n], ops[n], "Operator op" + std::to_string(n+1));
    all_ops_fops = merge(all_ops_fops, ops_fops[n]);
  }

  // Analyse structure of the Hilbert space
  hilbert_space_structure<HamiltonianType> hs_struct(
    h,
    fops,
    initial_state.get_full_hs(),
    all_ops_fops,
    is_zero_on_mesh<gf_mesh<retime>>(t_mesh)
  );

  // TODO

  time_container_t<NPoints> result;

  // TODO

  return result;
}

template<typename HamiltonianType>
expectval_container_t compute_expectval(static_operator_t const& op,
                                        init_state const& initial_state,
                                        HamiltonianType const& h,
                                        mesh_t_t const& t_mesh,
                                        solver_parameters_t const& params,
                                        mpi::communicator const& comm) {
  return compute_impl({op}, initial_state, h, t_mesh, params, comm);
}

//
// 2-point correlator
//

// Compute a 2-point correlator of operators 'op1' and 'op2' with their time
// arguments defined on a Cartesian product 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
correlator_2t_container_t compute_correlator_2t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                init_state const& initial_state,
                                                HamiltonianType const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t const& params,
                                                mpi::communicator const& comm) {
  return compute_impl({op1, op2}, initial_state, h, t_mesh, params, comm);
}

//
// 3-point correlator
//

// Compute a 3-point correlator of operators 'op1', 'op2' and 'op3' with their time
// arguments defined on a Cartesian product 't_mesh' x 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
correlator_3t_container_t compute_correlator_3t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                static_operator_t const& op3,
                                                init_state const& initial_state,
                                                HamiltonianType const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t const& params,
                                                mpi::communicator const& comm) {
  return compute_impl({op1, op2, op3}, initial_state, h, t_mesh, params, comm);
}

//
// Lesser GF
//

// Compute the lesser GF defined on a Cartesian product 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
block_gf_2t_t compute_g_l(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          HamiltonianType const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t const& params,
                          mpi::communicator const& comm) {
  // TODO: call compute_correlator_2t() and multiply result by (i/hbar)
}

//
// Greater GF
//

// Compute the greater GF defined on a Cartesian product 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
block_gf_2t_t compute_g_g(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          HamiltonianType const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t const& params,
                          mpi::communicator const& comm) {
  // TODO: call compute_correlator_2t() and multiply result by (-i/hbar)
}

//
// Susceptibility
//

// Compute the susceptibility defined on a Cartesian product 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
block_gf_2t_t compute_chi(gf_struct_t const& chi_struct,
                          init_state const& initial_state,
                          HamiltonianType const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t const& params,
                          mpi::communicator const& comm) {
  // TODO: call compute_correlator_2t() and multiply result by (-i/hbar)
}

//
// Explicit instantiations
//

// TODO: consider creating two translation units, one with explicit
// instantiations for HamiltonianType = time_expr_operator_t, and the other one
// for HamiltonianType = time_interp_operator_t.
//

expectval_container_t compute_expectval(static_operator_t const& op,
                                        init_state const& initial_state,
                                        time_expr_operator_t const& h,
                                        mesh_t_t const& t_mesh,
                                        solver_parameters_t const& params,
                                        mpi::communicator const& comm);
expectval_container_t compute_expectval(static_operator_t const& op,
                                        init_state const& initial_state,
                                        time_interp_operator_t const& h,
                                        mesh_t_t const& t_mesh,
                                        solver_parameters_t const& params,
                                        mpi::communicator const& comm);

correlator_2t_container_t compute_correlator_2t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                init_state const& initial_state,
                                                time_expr_operator_t const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t const& params,
                                                mpi::communicator const& comm);
correlator_2t_container_t compute_correlator_2t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                init_state const& initial_state,
                                                time_interp_operator_t const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t const& params,
                                                mpi::communicator const& comm);

correlator_3t_container_t compute_correlator_3t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                static_operator_t const& op3,
                                                init_state const& initial_state,
                                                time_expr_operator_t const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t const& params,
                                                mpi::communicator const& comm);
correlator_3t_container_t compute_correlator_3t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                static_operator_t const& op3,
                                                init_state const& initial_state,
                                                time_interp_operator_t const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t const& params,
                                                mpi::communicator const& comm);

block_gf_2t_t compute_g_l(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          time_expr_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t const& params,
                          mpi::communicator const& comm);
block_gf_2t_t compute_g_l(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          time_interp_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t const& params,
                          mpi::communicator const& comm);

block_gf_2t_t compute_g_g(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          time_expr_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t const& params,
                          mpi::communicator const& comm);
block_gf_2t_t compute_g_g(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          time_interp_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t const& params,
                          mpi::communicator const& comm);

block_gf_2t_t compute_chi(gf_struct_t const& chi_struct,
                          init_state const& initial_state,
                          time_expr_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t const& params,
                          mpi::communicator const& comm);
block_gf_2t_t compute_chi(gf_struct_t const& chi_struct,
                          init_state const& initial_state,
                          time_interp_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t const& params,
                          mpi::communicator const& comm);

} // namespace realevol
