/*******************************************************************************
 *
 * realevol - Real time evolution solver based on TRIQS
 *
 * Copyright (C) 2014-2022, I. Krivenko, M. Danilov, P. Kubiczek
 *
 * realevol is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * realevol is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * realevol. If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
#include <triqs/utility/first_include.hpp>

#include <algorithm>
#include <csignal>
#include <functional>
#include <iterator>
#include <limits>
#include <string>
#include <utility>
#include <vector>

#include <triqs/utility/signal_handler.hpp>

#include "array_utility.hpp"
#include "time_expr.hpp"
#include "time_interp.hpp"
#include "mesh_utils.hpp"
#include "hs_structure.hpp"
#include "time_point_selector.hpp"
#include "mpi_dispatcher.hpp"
#include "worldlines.hpp"
#include "wl_worker.hpp"
#include "compute.hpp"

namespace signal_handler = triqs::signal_handler;

static void check_signals() {
 if(signal_handler::received()) {
  int signal = signal_handler::last();
  if(signal == SIGINT) TRIQS_KEYBOARD_INTERRUPT;
  else                 TRIQS_RUNTIME_ERROR;
 }
}

namespace realevol {

template<typename HamiltonianType>
HamiltonianType try_reduce_to_constant(HamiltonianType const& op, mesh_t_t const& mesh) {
  HamiltonianType res;
  for(auto const& m : op) {
    auto new_coef = try_reduce_to_constant<typename HamiltonianType::scalar_t, mesh_t_t>(m.coef, mesh);
    HamiltonianType new_monomial(new_coef);
    for(auto const& c : m.monomial)
      new_monomial *= HamiltonianType::make_canonical(c.stat, c.dagger, c.indices);
    res += new_monomial;
  }
  return res;
}

template<std::size_t NPoints, typename HamiltonianType, typename TPointSelector>
void compute_impl(std::vector<std::array<static_operator_t, NPoints>> const& ops,
                  init_state const& initial_state,
                  HamiltonianType const& h_,
                  mesh_t_t const& t_mesh,
                  std::vector<time_container_t<NPoints>> & results,
                  solver_parameters_t<NPoints> const& params,
                  TPointSelector const& t_selector,
                  mpi::communicator const& comm
                 ) {
  assert(results.size() == ops.size());

  // Complete fundamental operator set of the problem
  auto const& fops = initial_state.get_fops();

  auto check_fops_subset = [&fops](fundamental_operator_set const& subfops,
                                   auto const& op,
                                   std::string const& op_name) {
    for(statistic_enum stat : {Fermion, Boson}) {
      for(auto it = subfops.begin(stat); it != subfops.end(stat); ++it) {
        if(!fops.has_indices(it->index, stat))
          TRIQS_RUNTIME_ERROR << op_name << " = " << op
                              << " contains a "
                              << (stat == Fermion ? "fermionic" : "bosonic")
                              << " index "
                              << it->index
                              << " incompatible with the initial problem";
      }
    }
  };

  signal_handler::start();

  // Check fundamental operator set generated by the Hamiltonian
  auto h_fops = h_.make_fundamental_operator_set();
  check_fops_subset(h_fops, h_, "Hamiltonian H");

  // Scan for the coefficients constant at all points of t_mesh,
  // and replace them with the corresponding constants
  auto h = try_reduce_to_constant(h_, t_mesh);

  if(params.verbosity >= 2)
    std::cout << "The Hamiltonian of the problem:" << std::endl
              << h << std::endl;

  // Fundamental operator sets generated by operators in 'ops'
  std::vector<std::array<fundamental_operator_set, NPoints>> ops_fops;
  ops_fops.reserve(ops.size());
  for(auto const& op_array : ops) {
    ops_fops.emplace_back(
      map_array<fundamental_operator_set>([](auto const& op) {
        return op.make_fundamental_operator_set();
      }, op_array)
    );
  }

  // Fundamental operator set generated by all elements of 'ops' together
  fundamental_operator_set all_ops_fops;
  for(std::size_t n = 0; n < ops_fops.size(); ++n) {
    auto const& op_array = ops_fops[n];
    for(std::size_t p = 0; p < NPoints; ++p) {
      check_fops_subset(
        op_array[p],
        ops[n][p],
        "[Computation " + std::to_string(n) + "] Operator op" + std::to_string(NPoints-p)
      );
      all_ops_fops = merge(all_ops_fops, op_array[p]);
    }
  }

  // Analyse structure of the Hilbert space
  hilbert_space_structure<HamiltonianType> hs_struct(
    h,
    fops,
    initial_state.get_full_hs(),
    all_ops_fops,
    is_zero_on_mesh<gf_mesh<retime>>(t_mesh)
  );

  check_signals();

  if(params.verbosity >= 1 && comm.rank() == 0)
    std::cout << "Found " << hs_struct.sub_hilbert_spaces.size()
              << " invariant subspaces." << std::endl;
  if(params.verbosity >= 2 && comm.rank() == 0) {
    for(auto const& sp : hs_struct.sub_hilbert_spaces) {
      std::cout << " Subspace " << sp.get_index() << " [" << sp.size() << "]: ";
      for(auto f : sp.get_all_fock_states()) std::cout << f << " ";
      std::cout << std::endl;
    }
  }

  // Check on which invariant subspaces the Hamiltonian is static
  auto static_pred = [](auto const& st) {
    bool c = true;
    foreach(st,[&c](uint32_t, auto const& te){
      if(!is_constant(te)) c = false;
    });
    return c;
  };

  auto is_static_sp = hs_struct.classify_subspaces(h, static_pred);

  if(params.verbosity >= 2 && comm.rank() == 0) {
    std::cout <<
      "The Hamiltonian is static on the following invariant subspaces";
    std::cout << std::endl << " ";
    for(long spn = 0; spn < is_static_sp.size(); ++spn) {
      if(is_static_sp[spn]) std::cout << spn << " ";
    }
    std::cout << std::endl;
  }

  // Compute subspace branching for the initial state
  auto const& subspaces = initial_state.get_sub_hilbert_spaces();
  auto subspace_branchings = hs_struct.compute_branchings(subspaces);

  check_signals();

  if(params.verbosity >= 2 && comm.rank() == 0) {
    std::cout << "Subspace branching for the initial state:" << std::endl;
    for(long spn = 0; spn < subspaces.size(); ++spn) {
      std::cout << " " << subspaces[spn].get_index() << " -> ";
      for(long spi : subspace_branchings[spn]) std::cout << spi << " ";
      std::cout << std::endl;
    }
  }

  // Generate all contributing world lines
  worldlines_maker<HamiltonianType> wlm(initial_state,
                                        hs_struct,
                                        subspace_branchings);

  std::vector<std::pair<worldline_desc_t<NPoints>,
                        std::reference_wrapper<time_container_t<NPoints>>>>
                        worldlines;
  for(std::size_t n = 0; n < ops.size(); ++n) {
    auto worldlines_n = wlm.make_worldlines(ops[n]);
    for(auto && wl : worldlines_n)
      worldlines.emplace_back(std::move(wl), results[n]);
  }

  if(params.verbosity >= 2 && comm.rank() == 0) {
    std::cout << "Processing world lines ("
              << worldlines.size() << " in total):" << std::endl;
    for(long i : range(worldlines.size())) {
      std::cout << "[" << i << "] " << worldlines[i].first << std::endl;
    }
  }
  if(worldlines.size() == 0) return;

  check_signals();

  auto lanczos_params = lanczos_params_t{params.lanczos_min_matrix_size,
                                         params.lanczos_gs_energy_tol,
                                         params.lanczos_max_krylov_dim};
  wl_worker<NPoints, HamiltonianType, TPointSelector> worker(
    initial_state,
    h,
    params.hbar,
    hs_struct,
    is_static_sp,
    t_selector,
    t_mesh,
    params.hamiltonian_interpol,
    lanczos_params
  );

  mpi_dispatcher<long> disp(comm, worldlines.size());

  check_signals();

  long nwl;
  while(true) {
    if((nwl = disp().value_or(-1)) == -1) break;
    worker(worldlines[nwl].first, worldlines[nwl].second.get());
    check_signals();
  }
  comm.barrier();

  check_signals();

  // Collect results from all MPI ranks
  for(auto & result : results)
    result = mpi_reduce(result, comm, 0, true);

  signal_handler::stop();

  if(params.verbosity >= 1 && comm.rank() == 0)
    std::cout << "Done" << std::endl;
}

//
// Expectation value
//

// Batch-compute expectation values of operators 'ops' as functions of time
template<typename HamiltonianType>
std::vector<expectval_container_t>
compute_expectval(std::vector<static_operator_t> const& ops,
                  init_state const& initial_state,
                  HamiltonianType const& h,
                  mesh_t_t const& t_mesh,
                  solver_parameters_t<1> const& params,
                  mpi::communicator const& comm) {
  std::vector<time_container_t<1>> results(ops.size(), t_mesh);
  time_point_selector<1> t_selector(params.t_ranges, params.delta_t_max);

  std::vector<std::array<static_operator_t, 1>> ops_as_arrays;
  ops_as_arrays.reserve(ops_as_arrays.size());
  std::transform(ops.begin(), ops.end(),
                 std::back_inserter(ops_as_arrays),
                 [](auto const& op){ return std::array<static_operator_t, 1>{op}; });
  compute_impl<1>(ops_as_arrays, initial_state, h, t_mesh, results, params, t_selector, comm);
  return results;
}

// Compute expectation value of operator 'op' as a function of time
template<typename HamiltonianType>
expectval_container_t compute_expectval(static_operator_t const& op,
                                        init_state const& initial_state,
                                        HamiltonianType const& h,
                                        mesh_t_t const& t_mesh,
                                        solver_parameters_t<1> const& params,
                                        mpi::communicator const& comm) {
  std::vector<time_container_t<1>> results{t_mesh};
  time_point_selector<1> t_selector(params.t_ranges, params.delta_t_max);
  compute_impl<1>({{op}}, initial_state, h, t_mesh, results, params, t_selector, comm);
  return std::move(results.back());
}

//
// 2-point correlator
//

// Batch-compute 2-point correlators of operators 'ops[i][0]' and 'ops[i][1]' with their time
// arguments defined on a Cartesian product 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
std::vector<correlator_2t_container_t>
compute_correlator_2t(std::vector<std::array<static_operator_t, 2>> ops,
                      init_state const& initial_state,
                      HamiltonianType const& h,
                      mesh_t_t const& t_mesh,
                      solver_parameters_t<2> const& params,
                      mpi::communicator const& comm) {
  for(auto & ops_array : ops)
    std::reverse(ops_array.begin(), ops_array.end());
  std::vector<time_container_t<2>> results(ops.size(), time_container_t<2>({t_mesh, t_mesh}));
  time_point_selector<2> t_selector(params.t_ranges, params.delta_t_max);
  compute_impl<2>(ops, initial_state, h, t_mesh, results, params, t_selector, comm);
  return results;
}

// Compute a 2-point correlator of operators 'op1' and 'op2' with their time
// arguments defined on a Cartesian product 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
correlator_2t_container_t compute_correlator_2t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                init_state const& initial_state,
                                                HamiltonianType const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t<2> const& params,
                                                mpi::communicator const& comm) {
  std::vector<time_container_t<2>> results{time_container_t<2>({t_mesh, t_mesh})};
  time_point_selector<2> t_selector(params.t_ranges, params.delta_t_max);
  compute_impl<2>({{op2, op1}}, initial_state, h, t_mesh, results, params, t_selector, comm);
  return std::move(results.back());
}

//
// 3-point correlator
//

// Batch-compute 3-point correlators of operators 'ops[i][0]', 'ops[i][1]' and 'ops[i][2]'
// with their time arguments defined on a Cartesian product 't_mesh' x 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
std::vector<correlator_3t_container_t>
compute_correlator_3t(std::vector<std::array<static_operator_t, 3>> ops,
                      init_state const& initial_state,
                      HamiltonianType const& h,
                      mesh_t_t const& t_mesh,
                      solver_parameters_t<3> const& params,
                      mpi::communicator const& comm) {
  for(auto & ops_array : ops)
    std::reverse(ops_array.begin(), ops_array.end());
  std::vector<time_container_t<3>> results(ops.size(), time_container_t<3>({t_mesh, t_mesh, t_mesh}));
  time_point_selector<3> t_selector(params.t_ranges, params.delta_t_max);
  compute_impl<3>(ops, initial_state, h, t_mesh, results, params, t_selector, comm);
  return results;
}

// Compute a 3-point correlator of operators 'op1', 'op2' and 'op3' with their time
// arguments defined on a Cartesian product 't_mesh' x 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
correlator_3t_container_t compute_correlator_3t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                static_operator_t const& op3,
                                                init_state const& initial_state,
                                                HamiltonianType const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t<3> const& params,
                                                mpi::communicator const& comm) {
  std::vector<time_container_t<3>> results{time_container_t<3>({t_mesh, t_mesh, t_mesh})};
  time_point_selector<3> t_selector(params.t_ranges, params.delta_t_max);
  compute_impl<3>({{op3, op2, op1}}, initial_state, h, t_mesh, results, params, t_selector, comm);
  return std::move(results.back());
}

//
// Initialize a GF container
//

void init_gf(time_container_view_t<2> f, time_point_selector_lower_triangle const& t_selector) {
  const double nan = std::numeric_limits<double>::quiet_NaN();
  for(auto t_tp : f.mesh()) {
    auto const& [t, tp] = t_tp.components_tuple();
    f[t_tp] = t_selector({t, tp}) ? .0 : dcomplex(nan, nan);
  }
}

//
// Change t <-> t' in a GF
//

auto swap_t_tp(gf_2t_view g) {
  auto result = gf_2t_t{g.mesh(), g.target_shape(), g.indices()};
  for(auto t_tp : g.mesh()) {
    auto const& [t, tp] = t_tp.components_tuple();
    result[t_tp] = g[{tp, t}];
  }
  return result;
}

//
// Restore anti-hermiticity of a GF
//
void restore_antihermiticity(gf_2t_view f,
                             time_point_selector_lower_triangle const& t_selector) {
  for(auto t_tp : f.mesh()) {
    auto const& [t, tp] = t_tp.components_tuple();
    if(t_selector({t, tp})) continue;
    // FIXME: Workaround for TRIQS issue #798
    //
    // https://github.com/TRIQS/triqs/issues/798
    f[t_tp] = -dagger(matrix<dcomplex>(f[{tp, t}]));
  }
}

//
// Compute block GF for a given gf_struct and time mesh
//

template<typename HamiltonianType, typename F>
block_gf_2t_t compute_block_gf(gf_struct_t const& gf_struct,
                               init_state const& initial_state,
                               HamiltonianType const& h,
                               mesh_t_t const& t_mesh,
                               solver_parameters_t<2> const& params,
                               time_point_selector_lower_triangle const& t_selector,
                               mpi::communicator const& comm,
                               F && f
                              ) {

  std::vector<std::array<static_operator_t, 2>> ops;
  std::vector<time_container_t<2>> gf_elements;

  for (auto const& bl : gf_struct) {
    int n = bl.second.size();

    for(int i1 = 0; i1 < n; ++i1) {
      for(int i2 = 0; i2 < n; ++i2) {
        ops.emplace_back(f(bl.first, bl.second[i1], bl.second[i2]));
        gf_elements.emplace_back(time_container_t<2>({t_mesh, t_mesh}));
        init_gf(gf_elements.back(), t_selector);
      }
    }
  }

  compute_impl<2>(ops,
                  initial_state,
                  h,
                  t_mesh,
                  gf_elements,
                  params,
                  t_selector,
                  comm);

  struct index_visitor  {
    std::vector<std::string> indices;
    void operator()(int i) { indices.push_back(std::to_string(i)); }
    void operator()(std::string s) { indices.push_back(s); }
  };

  std::vector<std::string> block_names;
  std::vector<gf_2t_t> g_blocks;

  auto element_it = gf_elements.begin();
  for (auto const& bl : gf_struct) {
    block_names.push_back(bl.first);
    int n = bl.second.size();

    index_visitor iv;
    for (auto const& ind : bl.second) { std::visit(iv, ind); }
    std::vector<std::vector<std::string>> indices{{iv.indices,iv.indices}};

    auto block = gf_2t_t{{t_mesh, t_mesh}, make_shape(n, n), indices};

    for(int i1 = 0; i1 < n; ++i1) {
      for(int i2 = 0; i2 < n; ++i2) {
        slice_target_to_scalar(block, i1, i2) = std::move(*element_it);
        ++element_it;
      }
    }
    g_blocks.emplace_back(std::move(block));
  }

  return make_block_gf(block_names, g_blocks);
}

//
// Lesser GF
//

// Compute the lesser GF defined on a Cartesian product 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
block_gf_2t_t compute_g_l(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          HamiltonianType const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t<2> const& params,
                          mpi::communicator const& comm) {

  time_point_selector_lower_triangle t_selector({params.t_ranges[1],
                                                 params.t_ranges[0]},
                                                 params.delta_t_max);

  auto f = [&](std::string const& block_name,
               std::variant<int, std::string> const& ind1,
               std::variant<int, std::string> const& ind2
              ) {
    auto op1 = c_dag(block_name, ind2);
    auto op2 = c(block_name, ind1);
    return std::array<static_operator_t, 2>{op2, op1};
  };
  auto g_l = compute_block_gf(gf_struct,
                              initial_state,
                              h,
                              t_mesh,
                              params,
                              t_selector,
                              comm,
                              f);

  g_l *= 1i / params.hbar;

  for(auto & g_l_block : g_l) {
    restore_antihermiticity(g_l_block, t_selector);
    g_l_block = swap_t_tp(g_l_block);
  }

  return g_l;
}

//
// Greater GF
//

// Compute the greater GF defined on a Cartesian product 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
block_gf_2t_t compute_g_g(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          HamiltonianType const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t<2> const& params,
                          mpi::communicator const& comm) {

  time_point_selector_lower_triangle t_selector(params.t_ranges, params.delta_t_max);

  auto f = [&](std::string const& block_name,
               std::variant<int, std::string> const& ind1,
               std::variant<int, std::string> const& ind2
              ) {
    auto op1 = c(block_name, ind1);
    auto op2 = c_dag(block_name, ind2);
    return std::array<static_operator_t, 2>{op2, op1};
  };
  auto g_g = compute_block_gf(gf_struct,
                              initial_state,
                              h,
                              t_mesh,
                              params,
                              t_selector,
                              comm,
                              f);

  g_g *= -1i / params.hbar;

  for(auto & g_g_block : g_g) {
    restore_antihermiticity(g_g_block, t_selector);
  }

  return g_g;
}

//
// Susceptibility
//

// Compute the susceptibility defined on a Cartesian product 't_mesh' x 't_mesh'.
template<typename HamiltonianType>
gf_2t_t compute_chi(chi_indices_t const& chi_indices,
                    init_state const& initial_state,
                    HamiltonianType const& h,
                    mesh_t_t const& t_mesh,
                    solver_parameters_t<2> const& params,
                    mpi::communicator const& comm) {

  int n_indices = chi_indices.size();

  time_point_selector_lower_triangle t_selector(params.t_ranges, params.delta_t_max);

  std::vector<std::array<static_operator_t, 2>> ops;
  ops.reserve(n_indices * n_indices);
  std::vector<time_container_t<2>> chi_elements;
  chi_elements.reserve(n_indices * n_indices);

  for(int i1 = 0; i1 < n_indices; ++i1) {
    for(int i2 = 0; i2 < n_indices; ++i2) {
      auto op1 = n(chi_indices[i1].first, chi_indices[i1].second);
      auto op2 = n(chi_indices[i2].first, chi_indices[i2].second);
      ops.emplace_back(std::array<static_operator_t, 2>{op2, op1});
      chi_elements.emplace_back(time_container_t<2>({t_mesh, t_mesh}));
      init_gf(chi_elements.back(), t_selector);
    }
  }

  compute_impl<2>(ops,
                  initial_state,
                  h,
                  t_mesh,
                  chi_elements,
                  params,
                  t_selector,
                  comm);

  struct index_visitor  {
    std::string operator()(int i) { return std::to_string(i); }
    std::string operator()(std::string s) { return s; }
  } iv;

  std::vector<std::string> indices1d;
  indices1d.reserve(n_indices);
  for (auto const& ind : chi_indices) {
    indices1d.push_back(ind.first + "," + std::visit(iv, ind.second));
  }
  std::vector<std::vector<std::string>> indices{{indices1d, indices1d}};

  auto chi = gf_2t_t{{t_mesh, t_mesh}, make_shape(n_indices, n_indices), indices};
  auto element_it = chi_elements.begin();
  for(int i1 = 0; i1 < n_indices; ++i1) {
    for(int i2 = 0; i2 < n_indices; ++i2) {
      slice_target_to_scalar(chi, i1, i2) = std::move(*element_it);
      ++element_it;
    }
  }

  chi *= -1i / params.hbar;

  restore_antihermiticity(chi, t_selector);

  return chi;
}

//
// Explicit instantiations
//

template
std::vector<expectval_container_t>
compute_expectval(std::vector<static_operator_t> const& ops,
                  init_state const& initial_state,
                  time_expr_operator_t const& h,
                  mesh_t_t const& t_mesh,
                  solver_parameters_t<1> const& params,
                  mpi::communicator const& comm);
template
std::vector<expectval_container_t>
compute_expectval(std::vector<static_operator_t> const& ops,
                  init_state const& initial_state,
                  time_interp_operator_t const& h,
                  mesh_t_t const& t_mesh,
                  solver_parameters_t<1> const& params,
                  mpi::communicator const& comm);

template
expectval_container_t compute_expectval(static_operator_t const& op,
                                        init_state const& initial_state,
                                        time_expr_operator_t const& h,
                                        mesh_t_t const& t_mesh,
                                        solver_parameters_t<1> const& params,
                                        mpi::communicator const& comm);
template
expectval_container_t compute_expectval(static_operator_t const& op,
                                        init_state const& initial_state,
                                        time_interp_operator_t const& h,
                                        mesh_t_t const& t_mesh,
                                        solver_parameters_t<1> const& params,
                                        mpi::communicator const& comm);

template
std::vector<correlator_2t_container_t>
compute_correlator_2t(std::vector<std::array<static_operator_t, 2>> ops,
                      init_state const& initial_state,
                      time_expr_operator_t const& h,
                      mesh_t_t const& t_mesh,
                      solver_parameters_t<2> const& params,
                      mpi::communicator const& comm);
template
std::vector<correlator_2t_container_t>
compute_correlator_2t(std::vector<std::array<static_operator_t, 2>> ops,
                      init_state const& initial_state,
                      time_interp_operator_t const& h,
                      mesh_t_t const& t_mesh,
                      solver_parameters_t<2> const& params,
                      mpi::communicator const& comm);

template
correlator_2t_container_t compute_correlator_2t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                init_state const& initial_state,
                                                time_expr_operator_t const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t<2> const& params,
                                                mpi::communicator const& comm);
template
correlator_2t_container_t compute_correlator_2t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                init_state const& initial_state,
                                                time_interp_operator_t const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t<2> const& params,
                                                mpi::communicator const& comm);

template
std::vector<correlator_3t_container_t>
compute_correlator_3t(std::vector<std::array<static_operator_t, 3>> ops,
                      init_state const& initial_state,
                      time_expr_operator_t const& h,
                      mesh_t_t const& t_mesh,
                      solver_parameters_t<3> const& params,
                      mpi::communicator const& comm);
template
std::vector<correlator_3t_container_t>
compute_correlator_3t(std::vector<std::array<static_operator_t, 3>> ops,
                      init_state const& initial_state,
                      time_interp_operator_t const& h,
                      mesh_t_t const& t_mesh,
                      solver_parameters_t<3> const& params,
                      mpi::communicator const& comm);

template
correlator_3t_container_t compute_correlator_3t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                static_operator_t const& op3,
                                                init_state const& initial_state,
                                                time_expr_operator_t const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t<3> const& params,
                                                mpi::communicator const& comm);
template
correlator_3t_container_t compute_correlator_3t(static_operator_t const& op1,
                                                static_operator_t const& op2,
                                                static_operator_t const& op3,
                                                init_state const& initial_state,
                                                time_interp_operator_t const& h,
                                                mesh_t_t const& t_mesh,
                                                solver_parameters_t<3> const& params,
                                                mpi::communicator const& comm);

template
block_gf_2t_t compute_g_l(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          time_expr_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t<2> const& params,
                          mpi::communicator const& comm);
template
block_gf_2t_t compute_g_l(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          time_interp_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t<2> const& params,
                          mpi::communicator const& comm);

template
block_gf_2t_t compute_g_g(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          time_expr_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t<2> const& params,
                          mpi::communicator const& comm);
template
block_gf_2t_t compute_g_g(gf_struct_t const& gf_struct,
                          init_state const& initial_state,
                          time_interp_operator_t const& h,
                          mesh_t_t const& t_mesh,
                          solver_parameters_t<2> const& params,
                          mpi::communicator const& comm);

template
gf_2t_t compute_chi(chi_indices_t const& chi_indices,
                    init_state const& initial_state,
                    time_expr_operator_t const& h,
                    mesh_t_t const& t_mesh,
                    solver_parameters_t<2> const& params,
                    mpi::communicator const& comm);
template
gf_2t_t compute_chi(chi_indices_t const& chi_indices,
                    init_state const& initial_state,
                    time_interp_operator_t const& h,
                    mesh_t_t const& t_mesh,
                    solver_parameters_t<2> const& params,
                    mpi::communicator const& comm);

} // namespace realevol
