/*******************************************************************************
 *
 * TRIQS: a Toolbox for Research in Interacting Quantum Systems
 *
 * Copyright (C) 2016 I. Krivenko
 *
 * TRIQS is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * TRIQS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * TRIQS. If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
#pragma once

#include <vector>
#include <iostream>
#include <triqs/hilbert_space/fundamental_operator_set.hpp>

#include "init_state.hpp"
#include "hs_structure.hpp"

namespace realevol {

// Describes a world line contributing to an obsearvable \mp
// Definition of contributions:
//
//  Greater component G^>_{index1,index2}(t,t'):
//   (-i/hbar) * <l| c_index1(t) |m><m| c^+_index2(t') |r> * weight
//
//  Lesser component G^<_{index1,index2}(t,t'):
//   (i/hbar) * <l| c^+_index2(t') |m><m| c_index1(t) |r> * weight
//
//  Susceptibility \chi_{index1,index2}(t,t'):
//   (-i/hbar) * <l| n_index1(t) |m><m| n_index2(t') |r> * weight
//
struct worldline_desc_t {

 /// Kind of observable
 enum {LesserGf, GreaterGf, Susceptibility} observable;

 /// First pair of indices of the observable
 indices_t index1;

 /// Second pair of indices of the observable
 indices_t index2;

 /// Block index of the observable (applies only to the GF)
 int block_index;

 /// First inner index of the observable
 int inner_index1;

 /// Second inner index of the observable
 int inner_index2;

 /// Index of weighted state in init_state
 int weighted_state_index;

 /// Left subspace index <l| (in the partition generated by h(t))
 long left_sp_index;

 /// Middle subspace index |m><m| (in the partition generated by h(t))
 long middle_sp_index;

 /// Right subspace index |r> (in the partition generated by h(t))
 long right_sp_index;

 friend std::ostream& operator<<(std::ostream& os, worldline_desc_t const& desc) {
  switch(desc.observable) {
   case GreaterGf:
    os << "-i <" << desc.left_sp_index << "| ";
    os << "c_{" << desc.index1 << "}(t)";
    os << " |" << desc.middle_sp_index << "><" << desc.middle_sp_index << "| ";
    os << "c^+_{" << desc.index2 << "}(t')";
    os << " |" << desc.right_sp_index << "> ";
    os << "(block_index=" << desc.block_index << ",";
    break;
   case LesserGf:
    os << "i <" << desc.left_sp_index << "| ";
    os << "c^+_{" << desc.index2 << "}(t')";
    os << " |" << desc.middle_sp_index << "><" << desc.middle_sp_index << "| ";
    os << "c_{" << desc.index1 << "}(t)";
    os << " |" << desc.right_sp_index << "> ";
    os << "(block_index=" << desc.block_index << ",";
    break;
   case Susceptibility:
    os << "-i <" << desc.left_sp_index << "| ";
    os << "n_{" << desc.index1 << "}(t)";
    os << " |" << desc.middle_sp_index << "><" << desc.middle_sp_index << "| ";
    os << "n_{" << desc.index2 << "}(t')";
    os << " |" << desc.right_sp_index << "> ";
    os << "(";
    break;
  }
  os << "i1=" << desc.inner_index1 << ",i2=" << desc.inner_index2 << "); ";
  os << "weighted_state " << desc.weighted_state_index;
  return os;
 }
};

/// Class to make a list of contributing worldlines
template<typename HamiltonianType>
class worldlines_maker {

 // Initial state
 init_state const& initial_state;
 // Hilbert space structure generated by h(t)
 hilbert_space_structure<HamiltonianType> const& hss;
 // Subspace branchings from the initial state to the time-dependent problem
 branchings_t const& branchings;

public:

 worldlines_maker(init_state const& initial_state,
                  hilbert_space_structure<HamiltonianType> const& hss,
                  branchings_t const& branchings) :
 initial_state(initial_state), hss(hss), branchings(branchings) {}

 auto make_gf_worldlines(gf_struct_t const& gf_struct, bool is_greater) {
  auto const& c_conn = hss.annihilation_connection[Fermion];
  auto const& cdag_conn = hss.creation_connection[Fermion];

  std::vector<worldline_desc_t> res;
  auto const& fops = initial_state.get_fops();
  auto const& wst = initial_state.get_weighted_states();

  int block_index = 0;
  for(auto const& block : gf_struct) {
   int bl_size = block.second.size();
   for (int inner_index1 = 0; inner_index1 < bl_size; ++inner_index1) {
    indices_t index1 = {block.first, block.second[inner_index1]};
    int n1 = fops[index1]; // linear_index of c
    for (int inner_index2 = 0; inner_index2 < bl_size; ++inner_index2) {
     indices_t index2 = {block.first, block.second[inner_index2]};
     int n2 = fops[index2]; // linear_index of c^+

     for(int wst_i = 0; wst_i < wst.size(); ++wst_i) {
      auto const& st = wst[wst_i];
      auto const& branching = branchings[st.state.get_hilbert().get_index()];
      for(long right_sp_index : branching) {
       // Checking selection rule for <middle_sp_index| |right_sp_index>
       long middle_sp_index = is_greater ? cdag_conn(n2,right_sp_index) :
                                           c_conn(n1,right_sp_index);
       if(middle_sp_index == -1) continue;
       // Checking selection rule for <left_sp_index| |middle_sp_index>
       long left_sp_index = is_greater ? c_conn(n1,middle_sp_index) :
                                         cdag_conn(n2,middle_sp_index);
       if(left_sp_index == -1 || !branching.count(left_sp_index)) continue;

       res.push_back({is_greater ?
                      worldline_desc_t::GreaterGf : worldline_desc_t::LesserGf,
                      index1, index2,
                      block_index, inner_index1, inner_index2,
                      wst_i, left_sp_index, middle_sp_index, right_sp_index});
      }
     }
    }
   }
   ++block_index;
  }

  return res;
 }

 auto make_chi_worldlines(chi_indices_t const& chi_indices) {
  auto const& c_conn = hss.annihilation_connection[Fermion];

  std::vector<worldline_desc_t> res;
  auto const& fops = initial_state.get_fops();
  auto const& wst = initial_state.get_weighted_states();

  int chi_size = chi_indices.size();
  for (int inner_index1 = 0; inner_index1 < chi_size; ++inner_index1) {
    indices_t index1 = {chi_indices[inner_index1].first,
                        chi_indices[inner_index1].second};
    int n1 = fops[index1]; // linear_index of n1
    for (int inner_index2 = 0; inner_index2 < chi_size; ++inner_index2) {
     indices_t index2 = {chi_indices[inner_index2].first,
                         chi_indices[inner_index2].second};
     int n2 = fops[index2]; // linear_index of n2

     for(int wst_i = 0; wst_i < wst.size(); ++wst_i) {
      auto const& st = wst[wst_i];
      auto const& branching = branchings[st.state.get_hilbert().get_index()];
      for(long right_sp_index : branching) {
       // Checking selection rule for <middle_sp_index| |right_sp_index>
       long middle_sp_index = (c_conn(n2,right_sp_index) != -1) ? right_sp_index : -1;
       if(middle_sp_index == -1) continue;
       // Checking selection rule for <left_sp_index| |middle_sp_index>
       long left_sp_index = (c_conn(n1,middle_sp_index) != -1) ? middle_sp_index : -1;
       if(left_sp_index == -1 || !branching.count(left_sp_index)) continue;

       res.push_back({worldline_desc_t::Susceptibility,
                      index1, index2,
                      0, inner_index1, inner_index2,
                      wst_i, left_sp_index, middle_sp_index, right_sp_index});
      }
     }
   }
  }

  return res;
 }

};

}
