/*******************************************************************************
 *
 * realevol - Real time evolution solver based on TRIQS
 *
 * Copyright (C) 2014-2020, I. Krivenko, M. Danilov, P. Kubiczek
 *
 * realevol is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * realevol is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * realevol. If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
#pragma once

#include <array>
#include <complex>
#include <iostream>
#include <vector>

#include "init_state.hpp"
#include "hs_structure.hpp"

namespace realevol {

//
// worldline_desc_t<N> describes a contribution to the dynamical trace
//
//  \Tr[\hat \rho_0 \hat A_1(t_1) \hat A_2(t_2) \ldots \hat A_N(t_N)]
//
// Each such contribution can be computed independently of all others and has
// the following form,
//
// factor * <sp_N| \hat M_{N-1}(t_{N-1}) |sp_{N-1}> *
//          <sp_{N-1}| \hat M_{N-2} |sp_{N-2}>
//          \ldots
//          <sp_1| \hat M_0 |sp_0> * weight
//
// Here, M_n are monomials made of canonical operators.

template<std::size_t NPoints> struct worldline_desc_t {

  /// Kind of observable
  enum {LesserGf, GreaterGf, Susceptibility} observable; // TODO: remove

  /// Block index of the observable (applies only to the GF)
  int block_index; // TODO: remove

  /// First inner index of the observable
  int inner_index1; // TODO: remove

  /// Second inner index of the observable
  int inner_index2; // TODO: remove

  // Numerical prefactor of this contribution
  std::complex<double> factor;

  /// List of monomials M_n
  std::array<monomial_t, NPoints> M;

  /// Subspace indices sp_n (in the partition generated by h(t))
  std::array<long, NPoints + 1> sp_indices;

  /// Index of weighted state in init_state
  int weighted_state_index;

  friend std::ostream& operator<<(std::ostream& os,
                                  worldline_desc_t const& desc) {
    os << desc.factor << " ";
    for(int n = NPoints - 1; n >= 0; --n) {
      os << "<" << desc.sp_indices[n + 1] << "|";
      os << desc.M[n];
      os << "|" << desc.sp_indices[n] << ">";
    }
    os << " weighted_state " << desc.weighted_state_index;
    return os;
  }
};

/// Class to make a list of contributing worldlines
template<typename HamiltonianType>
class worldlines_maker {

  // Initial state
  init_state const& initial_state;
  // Hilbert space structure generated by h(t)
  hilbert_space_structure<HamiltonianType> const& hss;
  // Subspace branchings from the initial state to the time-dependent problem
  branchings_t const& branchings;
  // Planck's constant
  double hbar;

public:

  worldlines_maker(init_state const& initial_state,
                   hilbert_space_structure<HamiltonianType> const& hss,
                   branchings_t const& branchings,
                   double hbar) :
  initial_state(initial_state), hss(hss), branchings(branchings), hbar(hbar) {}

  std::vector<worldline_desc_t<2>>
  make_gf_worldlines(gf_struct_t const& gf_struct, bool is_greater);
  std::vector<worldline_desc_t<2>>
  make_chi_worldlines(chi_indices_t const& chi_indices);
};

} // namespace realevol
