/*******************************************************************************
 *
 * TRIQS: a Toolbox for Research in Interacting Quantum Systems
 *
 * Copyright (C) 2016 I. Krivenko
 *
 * TRIQS is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * TRIQS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * TRIQS. If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
#include <triqs/utility/first_include.hpp>

#include <cmath>

#include "init_state.hpp"
#include "lanczos_worker.hpp"

namespace realevol {

static_operator_t make_static_op(operator_t const& op, std::string const& error_message) {
 static_operator_t static_op;
 for(auto const& m : op) {
  if(!is_constant(m.coef)) TRIQS_RUNTIME_ERROR << error_message;
  auto new_coef = m.coef(0);
  static_operator_t new_monomial(new_coef);
  for(auto const& c : m.monomial)
   new_monomial *= static_operator_t::make_canonical(c.stat, c.dagger, c.indices);
  static_op += new_monomial;
 }
 return static_op;
}

std::vector<init_state_t> init_state_pure(operator_t const& generator, hilbert_space_structure & hss) {

 // Static version of generator
 auto gen = make_static_op(generator, "Generating operator must be time-independent!");

 std::vector<init_state_t> states = {{{}, 1.0}};
 auto & parts = states[0].parts;

 state_on_space_t vacuum(hss.full_hs);
 vacuum(fock_state_t(0)) = 1;

 static_op_on_space_t imp_gen(gen, hss.fops, hss.full_hs);
 auto init_state = imp_gen(vacuum);

 foreach(init_state, [&parts,&hss](fock_state_t f, dcomplex a){
  auto spn = hss.partition.lookup_basis_state(f);
  auto const& sp = hss.sub_hilbert_spaces[spn];
  auto ins = parts.emplace(spn, sp);
  (ins.first->second)(sp.get_state_index(f)) = a;
 });

 return states;
}

std::vector<init_state_t> init_state_thermal(operator_t const& h0, hilbert_space_structure & hss,
                                             double beta, double temperature_cutoff) {

 // Static version the equilibrium Hamiltonian is static
 auto h0_ = make_static_op(h0, "Equilibrium Hamiltonian operator must be time-independent!");

 // Hilbert space structure generated by the equilibrium Hamiltonian
 hilbert_space_structure hss0(h0, hss.fops, hss.full_hs, false);

 // Time complexity on Lanczos iterations: O(k(nnz + n))
 // n - matrix size, nnz - number of non-zero elements, k - number of Krylov basis vectors
 // J. Chen and Y. Saad, "Lanczos Vectors versus Singular Vectors for Effective Dimension Reduction,"
 // IEEE Transactions on Knowledge and Data Engineering, vol. 21, no. 8, pp. 1091-1103, Aug. 2009.

 // Iterate over all sectors of h0
 for(auto const& sp : hss0.sub_hilbert_spaces) {
  static_op_on_subspace_t imp_h0(h0_, hss0.fops, hss.full_hs);

  auto lw = lanczos_worker<static_op_on_subspace_t, state_on_subspace_t>(imp_h0,1e-10);

  state_on_subspace_t psi0(sp); psi0(0) = 1.0;
  lw(psi0);

  std::cout << lw.values() << std::endl;
 }

 std::vector<init_state_t> states;
 // TODO

 return states;
}

}
