#pragma once

#include <string>
#include <vector>
#include <map>
#include <algorithm>

#include <triqs/draft/hilbert_space_tools/fundamental_operator_set.hpp>
#include <triqs/draft/hilbert_space_tools/hilbert_space.hpp>
#include <triqs/draft/hilbert_space_tools/imperative_operator.hpp>

#include "solve_parameters.hpp"
#include "mesh_container.hpp"
#include "mesh_container_cyclic.hpp"

namespace realevol {

using namespace triqs::utility;
using std::complex;

template<bool ComplexOperators, typename Mesh>
class observables_worker {

using op_on_space_t = imperative_operator<hilbert_space,operator_coeff_t<ComplexOperators>,false>;
using state_on_space_t = state<hilbert_space,complex<double>,false>;
using state_on_subspace_t = state<sub_hilbert_space,complex<double>,false>;

using space_partition_t = space_partition<state<hilbert_space,operator_coeff_t<ComplexOperators>,true>,op_on_space_t>;
using block_mapping_t = typename space_partition_t::block_mapping_t;

block_mapping_t connections;
std::vector<mesh_container_cyclic<state_on_subspace_t,Mesh>> const& solutions;
hilbert_space hs;
long cur_time_point;

state_on_space_t zero_state;

public:

using results_t = std::map<std::string,mesh_container<double,Mesh>>;

observables_worker(Mesh const& mesh,
                   std::map<std::string,operator_t<ComplexOperators>> const& observables,
                   std::vector<mesh_container_cyclic<state_on_subspace_t,Mesh>> const& solutions,
                   fundamental_operator_set const& fops,
                   space_partition_t & SP,
                   std::vector<std::pair<int,int>> const& subspace_disp_table
                  ) :
    solutions(solutions),
    hs(fops),
    zero_state(hs),
    cur_time_point(0)
{
    results = init_results(mesh, observables);

    // Find all subspace connections generated by the observables
    for(auto const& obs : observables) {
        auto const& op = obs.second;

        if(!(op - dagger(op)).is_zero()) TRIQS_RUNTIME_ERROR << "Observable '" << obs.first << "' is not Hermitian!";

        auto conn = SP.find_mappings({obs.second,fops});
        std::set_union(std::begin(connections), std::end(connections),
                       std::begin(conn), std::end(conn),
                       std::inserter(connections, std::begin(connections)));
    }

    // Filter out connections between trivial subspaces
    for(auto it = std::begin(connections); it != std::end(connections); ++it) {
        if(subspace_disp_table[it->first].first == -1 ||
           subspace_disp_table[it->second].first == -1) {
            connections.erase(it);
        }
    }

}

void operator()(long num_time_points) {
    for(;num_time_points>0; --num_time_points) {
        
        //state_on_space_t
        
        cur_time_point++;
    }
}

results_t get_results() { return results; }

static results_t init_results(Mesh const& mesh, std::map<std::string,operator_t<ComplexOperators>> const& observables) {
    results_t res;
    for(auto const& obs : observables) res.emplace(obs.first,mesh_container<double,Mesh>(mesh,.0));
    return res;
}

private:
    results_t results;
};

}
