#pragma once

#include <string>
#include <vector>
#include <set>
#include <map>
#include <algorithm>

#include "common.hpp"
#include "solve_parameters.hpp"
#include "mesh_container.hpp"
#include "mesh_container_cyclic.hpp"

namespace realevol {

template<bool ComplexOp> class simulation;

template<bool ComplexOp, typename Mesh>
class observables_worker {

std::vector<mesh_container_cyclic<state_on_subspace_t,Mesh>> const& solution_parts;
hilbert_space hs;
Mesh const& mesh;
long cur_time_point;

state_on_space_t zero_state;

boost::mpi::communicator const& comm;
std::set<int> relevant_local_parts;     // indices in solution_parts
std::multimap<int,int> parts_to_send;   // index in solution_parts -> destination rank
int num_parts_to_recv;                  // the number of bra-vector parts to receive

static const int mpi_tag = 1;

public:

struct observable_data_t {
    std::string name;
    op_on_space_t<ComplexOp> op;
    mesh_container<double,Mesh> result;
    int mesh_downsampling;  // reserved
};

observables_worker(Mesh const& mesh,
                   std::map<std::string,operator_t<ComplexOp>> const& observables,
                   std::vector<mesh_container_cyclic<state_on_subspace_t,Mesh>> const& solution_parts,
                   simulation<ComplexOp> & sim
                  ) :
    mesh(mesh),
    solution_parts(solution_parts),
    hs(sim.fops),
    zero_state(hs),
    comm(sim.comm),
    cur_time_point(0)
{
    typename space_partition_t<ComplexOp>::block_mapping_t connections;

    for(auto const& obs : observables) {
        if(!(obs.second - dagger(obs.second)).is_zero()) TRIQS_RUNTIME_ERROR << "Observable '" << obs.first << "' is not Hermitian!";

        // Fill 'data'
        op_on_space_t<ComplexOp> op(obs.second,sim.fops);
        data.push_back({obs.first, op, mesh_container<double,Mesh>(mesh,.0), 1});

        // Find all subspace connections generated by the observables
        auto conn = sim.SP.find_mappings(op);
        std::set_union(std::begin(connections), std::end(connections),
                       std::begin(conn), std::end(conn),
                       std::inserter(connections, std::begin(connections)));
    }

    // Filter out connections between trivial subspaces
    for(auto it = std::begin(connections); it != std::end(connections); ++it) {
        if(sim.subspace_disp_table[it->first].rank == -1 ||
           sim.subspace_disp_table[it->second].rank == -1) {
            connections.erase(it);
        }
    }

    // Fill relevant_local_parts, parts_to_send and num_parts_to_recv
    num_parts_to_recv = 0;
    for(auto const& conn : connections) {
        auto const& ri = sim.subspace_disp_table[conn.first];
        if(ri.rank == comm.rank()) {
            relevant_local_parts.insert(ri.local_index);
            parts_to_send.emplace(ri.local_index,sim.subspace_disp_table[conn.second].rank);
        } else {
            if(sim.subspace_disp_table[conn.second].rank == comm.rank()) num_parts_to_recv++;
        }
    }
}

void operator()(long num_time_points) {
    if(data.empty()) {
        cur_time_point += num_time_points;
        return;
    }
    for(; num_time_points>0 && cur_time_point < mesh.size();
        --num_time_points, ++cur_time_point) {

        auto t = mesh[cur_time_point];
        state_on_space_t bra(zero_state), ket(zero_state);

        fill_ket(ket);
        fill_bra(bra);

        for(auto & d : data) d.result[cur_time_point] = std::real(dot_product(bra,d.op(ket,t)));
    }
}

results_t<Mesh> get_results() {
    results_t<Mesh> results;
    for(auto const& d : data) results.emplace(d.name,d.result);
    return results;
}

private:

    void embed_state(state_on_subspace_t const& src, state_on_space_t & dst) const {
        auto const& src_hs = src.get_hilbert();
        foreach(src,[&dst,&src_hs](int i, dcomplex v){ dst(src_hs.get_fock_state(i)) = v; });
    }

    // Fill the ket vector (local-only operation)
    void fill_ket(state_on_space_t & ket) const {
        for(auto index : relevant_local_parts) {
            auto const& sub_st = solution_parts[index][cur_time_point];
            embed_state(sub_st,ket);
        }
    }

    // Fill the bra vector
    void fill_bra(state_on_space_t & bra) const {
        // isend + local fill phase
        for(auto const& p : parts_to_send) {
            if(p.second == comm.rank())
                embed_state(solution_parts[p.first][cur_time_point],bra);
            // FIXME
            //else
            //    comm.isend(p.second,mpi_tag,solution_parts[p.first][cur_time_point]);
        }

        // recv phase
        int n = num_parts_to_recv;
        while(n) {
            state_on_subspace_t sub_st;
            // FIXME
            //comm.recv(boost::mpi::any_source,mpi_tag,sub_st);
            embed_state(sub_st,bra);
            n--;
        }

        comm.barrier();
    }

    std::vector<observable_data_t> data;
};

}
