#pragma once

#include <string>
#include <map>
#include <algorithm>

#include <triqs/draft/hilbert_space_tools/fundamental_operator_set.hpp>
#include <triqs/draft/hilbert_space_tools/hilbert_space.hpp>
#include <triqs/draft/hilbert_space_tools/imperative_operator.hpp>

#include "solve_parameters.hpp"
#include "mesh_container.hpp"

namespace realevol {

using namespace triqs::utility;


// template<typename ObservablesType, typename SpacePartitionType>
// block_mapping_t find_all_connections(ObservablesType const& observables,
//                                      fundamental_operator_set const& fops,
//                                      SpacePartitionType & SP) {
//     block_mapping_t obs_connections;
//     for(auto const& obs : observables) {
//         auto conn = SP.find_mappings({obs.second,fops});
// 
//         std::set_union(std::begin(obs_connections), std::end(obs_connections),
//                        std::begin(conn), std::end(conn),
//                        std::inserter(obs_connections, std::begin(obs_connections)));
//     }
//     return obs_connections;
// }
// 
// void filter_connections(block_mapping_t & connections, std::vector<std::pair<int,int>> const& subspace_disp_table) {
//     for(auto it = std::begin(connections); it != std::end(connections); ++it) {
//         if(subspace_disp_table[it->first].first == -1 ||
//            subspace_disp_table[it->second].first == -1) {
//             connections.erase(it);
//         }
//     }
// }

template<bool ComplexOperators, typename Mesh>
class observables_worker {

using op_on_space_t = imperative_operator<hilbert_space,operator_coeff_t<ComplexOperators>,false>;

using space_partition_t = space_partition<state<hilbert_space,operator_coeff_t<ComplexOperators>,true>,op_on_space_t>;
using block_mapping_t = typename space_partition_t::block_mapping_t;

block_mapping_t connections;

public:

using results_t = std::map<std::string,mesh_container<double,Mesh>>;

observables_worker(Mesh const& mesh,
                   std::map<std::string,operator_t<ComplexOperators>> const& observables) {
    results = init_results(mesh, observables);
}

static results_t init_results(Mesh const& mesh, std::map<std::string,operator_t<ComplexOperators>> const& observables) {
    results_t res;
    for(auto const& obs : observables) res.emplace(obs.first,mesh_container<double,Mesh>(mesh,.0));
    return res;
}

results_t get_results() { return results; }

private:
    results_t results;
};

    // Find all subspace connections generated by the observables
    //obs_connections = find_all_connections(p.observables,fops,SP);

    // Filter out connections between trivial subspaces
    //filter_connections(obs_connections,subspace_disp_table);

}
