#include "realevol.hpp"
#include "uniform_mesh.hpp"

using namespace triqs::utility;

namespace realevol {

#define SOLVER_METHOD(M)    template<typename Mesh, bool ComplexOperators> auto solver<Mesh,ComplexOperators>::M 

SOLVER_METHOD(fill_fops(fundamental_operator_set & fops, operator_t const& op) -> void) {
    for(auto const& term : op) {
        for (auto const& canonical_op : term.monomial) {
            fops.insert(canonical_op.indices);
        }
    }
}

SOLVER_METHOD(solve(operator_t h, parameters_t params, dict_t<operator_t> observables) -> void){

    // Fill the fundamental operator set from H and the observables
    fundamental_operator_set fops;
    fill_fops(fops,h);
    for(auto const& ob : observables) fill_fops(fops,ob.second);

    if(static_cast<int>(params["verbosity"]) > 0){
        std::cout << "Hilbert space is generated by " << fops.n_operators() << " C / C^+ pairs:" << std::endl;
        for(auto const& op : fops){
            for(auto const& i : op.index) std::cout << i << '\t';
            std::cout << std::endl;
        }
    }
}

SOLVER_METHOD(solve_parameters() -> parameters_t) {
    boost::mpi::communicator world;
    auto pdef = parameters_t{};

    pdef.add_field("verbosity", (world.rank()==0 ? int(3) : int(0)), "Verbosity level")
        //.add_field("mesh", triqs::params::no_default<Mesh>(), "Time mesh to solve the Schroedinger equation")
        .add_field("planck_constant", double(1.0), "Planck constant");
        //.add_field("mesh_downsampling", dict_t<int>({}), "Mesh downsampling factors for the observables");

    return pdef;
}

SOLVER_METHOD(help() -> void) {
// TODO
}

#undef SOLVER_METHOD

// Explicit instantiations
// Add more mesh types later if needed
template class solver<uniform_mesh<>,false>;
template class solver<uniform_mesh<>,true>;

}