#include "realevol.hpp"

#include <triqs/gfs/domains/R.hpp>
#include <triqs/gfs/meshes/segment.hpp>
#include <triqs/draft/hilbert_space_tools/imperative_operator.hpp>

#include "space_partition.hpp"
#include "schroedinger_worker.hpp"

using namespace triqs::utility;

namespace realevol {

#define SOLVER_METHOD(RETTYPE,NAME)    template<typename Mesh, bool ComplexOperators> RETTYPE solver<Mesh,ComplexOperators>::NAME
#define AT_VERBOSITY(V)                if(static_cast<int>(params["verbosity"]) >= V)

SOLVER_METHOD(,solver(std::set<std::string> const& operator_indices)) :
    fops(operator_indices), hs(fops), init_state(hs)
{
}

SOLVER_METHOD(void,solve(operator_t h, parameters_t params, dict_t<operator_t> observables)){
    AT_VERBOSITY(1){
        std::cout << "Hilbert space is generated by " << fops.size() << " C/C^+ pairs:" << std::endl;
        for(auto const& op : fops){
            for(auto const& i : op.index) std::cout << i << '\t';
            std::cout << std::endl;
        }
    }

    imperative_operator<hilbert_space,operator_coeff_t,false> hamiltonian(h, fops);
    state<hilbert_space,operator_coeff_t,true> st(hs);

    // Split the Hilbert space
    space_partition<decltype(st),decltype(hamiltonian)> SP(st, hamiltonian);

    // Fill subspaces
    std::vector<sub_hilbert_space> subspaces;
    for (int n = 0; n < SP.n_subspaces(); ++n) subspaces.emplace_back(n);
    foreach(SP, [&subspaces](fock_state_t s, int spn) { subspaces[spn].add_fock_state(s); });

    AT_VERBOSITY(1){
        std::cout << "Found " << subspaces.size() << " invariant subspaces" << std::endl;
        AT_VERBOSITY(2){
            for(int spn = 0; spn < subspaces.size(); ++spn){
                std::cout << "States in subspace " << spn << ": ";
                for(auto s : subspaces[spn].get_all_fock_states()) std::cout << s << " ";
                std::cout << std::endl;
            }
        }
    }

    // Construct workers to solve Schroedinger equation
//     for(auto sp : subspaces) {
//         schroedinger_worker<> worker();
//     }

}

SOLVER_METHOD(parameters_t,solve_parameters()) {
    boost::mpi::environment env;
    boost::mpi::communicator world;

    auto pdef = parameters_t{};

    pdef.add_field("verbosity", (world.rank()==0 ? int(1) : int(0)), "Verbosity level")
        //.add_field("mesh", triqs::params::no_default<Mesh>(), "Time mesh to solve the Schroedinger equation")
        .add_field("planck_constant", double(1.0), "Planck constant");
        //.add_field("ode_solve_method", triqs::params::no_default<ode_solve_method>(), "Method to solve Schroedinger equation");
        //.add_field("mesh_downsampling", dict_t<int>({}), "Mesh downsampling factors for the observables");

    return pdef;
}

SOLVER_METHOD(void,help()) {
// TODO
}

#undef SOLVER_METHOD

// Explicit instantiations
// Add more mesh types later if needed
template class solver<triqs::gfs::segment_mesh,false>;
template class solver<triqs::gfs::segment_mesh,true>;

}