#include "realevol.hpp"

#include <triqs/gfs/domains/R.hpp>
#include <triqs/gfs/meshes/segment.hpp>

using namespace triqs::utility;

namespace realevol {

#define SOLVER_METHOD(RETTYPE,NAME)    template<typename Mesh, bool ComplexOperators> RETTYPE solver<Mesh,ComplexOperators>::NAME

SOLVER_METHOD(,solver(std::set<std::string> const& operator_indices)) :
    fops(operator_indices), hs(fops), init_state(hs)
{
}

SOLVER_METHOD(void,solve(operator_t h, parameters_t params, dict_t<operator_t> observables)){
    if(static_cast<int>(params["verbosity"]) > 0){
        std::cout << "Hilbert space is generated by " << fops.size() << " C / C^+ pairs:" << std::endl;
        for(auto const& op : fops){
            for(auto const& i : op.index) std::cout << i << '\t';
            std::cout << std::endl;
        }
    }
}

SOLVER_METHOD(parameters_t,solve_parameters()) {
    boost::mpi::environment env;
    boost::mpi::communicator world;

    auto pdef = parameters_t{};

    pdef.add_field("verbosity", (world.rank()==0 ? int(3) : int(0)), "Verbosity level")
        //.add_field("mesh", triqs::params::no_default<Mesh>(), "Time mesh to solve the Schroedinger equation")
        .add_field("planck_constant", double(1.0), "Planck constant");
        //.add_field("mesh_downsampling", dict_t<int>({}), "Mesh downsampling factors for the observables");

    return pdef;
}

SOLVER_METHOD(void,help()) {
// TODO
}

#undef SOLVER_METHOD

// Explicit instantiations
// Add more mesh types later if needed
template class solver<triqs::gfs::segment_mesh,false>;
template class solver<triqs::gfs::segment_mesh,true>;

}