#pragma once

#include <complex>
#include <string>
#include <vector>
#include <map>
#include <boost/mpi/communicator.hpp>
#include <boost/variant/static_visitor.hpp>

#include <triqs/draft/hilbert_space_tools/fundamental_operator_set.hpp>
#include <triqs/draft/hilbert_space_tools/hilbert_space.hpp>
#include <triqs/draft/hilbert_space_tools/imperative_operator.hpp>
#include <triqs/draft/hilbert_space_tools/state.hpp>
#include <triqs/utility/draft/numeric_ops.hpp>

#include "any_mesh.hpp"
#include "mesh_container.hpp"
#include "space_partition.hpp"
#include "lpt_scheduler.hpp"
#include "schroedinger_worker.hpp"

namespace realevol {

using triqs::utility::project;
using triqs::utility::many_body_operator;
using triqs::utility::fundamental_operator_set;
using triqs::utility::hilbert_space;
using triqs::utility::sub_hilbert_space;
using triqs::utility::imperative_operator;
using triqs::utility::state;
using triqs::utility::fock_state_t;

using results_t = std::map<std::string,any_mesh_container_t<double>>;

template<bool ComplexOperators>
class simulation : public boost::static_visitor<results_t> {

    fundamental_operator_set fops;
    std::vector<sub_hilbert_space> subspaces;
    std::vector<state<sub_hilbert_space,std::complex<double>,false>> sub_init_states;
    imperative_operator<sub_hilbert_space,operator_coeff_t<ComplexOperators>,false> hamiltonian;
    double hbar;
    ode_solve_method method;
    long stored_psi_values;

    // MPI data structures
    boost::mpi::communicator comm;
    int my_rank;
    std::vector<schedule_t<int>> schedules;
    std::vector<std::pair<int,int>> subspace_disp_table;  // subspace -> (rank,local id)
    const int missing_rank = -1;

public:

    using params_t = solve_parameters_t<ComplexOperators>;

    simulation(boost::mpi::communicator const& comm,
               fundamental_operator_set const& fops,
               hilbert_space const& hs,
               state<hilbert_space,std::complex<double>,false> const& init_state,
               params_t const& p
              ) :
        comm(comm), my_rank(comm.rank()),
        fops(fops),
        hamiltonian(p.h,fops), hbar(p.hbar),
        method(p.method), stored_psi_values(p.stored_psi_values)
    {
        if(p.verbosity >= 1){
            std::cout << "Hilbert space is generated by " << fops.size() << " C/C^+ pairs:" << std::endl;
            for(auto const& op : fops){
                for(auto const& i : op.index) std::cout << i << " ";
                std::cout << std::endl;
            }
        }

        partition(fops,hs,p);
        distribute_jobs(init_state,p);
    }

    template<typename Mesh> results_t operator()(Mesh const& m) {

        stored_psi_values = std::min(stored_psi_values,m.size());

        std::map<std::string,mesh_container<double,Mesh>> results;

                // TODO: pass results to run_my_jobs()

        switch(method) {
            case method_runge_kutta:
                run_my_jobs<Mesh,method_runge_kutta>(m);
                break;
            case method_lanczos:
                run_my_jobs<Mesh,method_lanczos>(m);
                break;
            default:
                TRIQS_RUNTIME_ERROR << "Unknown method to solve the Schroedinger equation: " << method;
        }

        comm.barrier();


        // TODO: collect results
        results_t variant_results;
        for(auto const& r : results) variant_results.emplace(r);
        return variant_results;
    }

private:

    void partition(fundamental_operator_set const& fops, hilbert_space const& hs, params_t const& p) {

        imperative_operator<hilbert_space,operator_coeff_t<ComplexOperators>,false> h(p.h,fops);
        state<hilbert_space,operator_coeff_t<ComplexOperators>,true> st(hs);

        // Split the Hilbert space
        space_partition<decltype(st),decltype(h)> SP(st, h);

        // Fill subspaces
        for (int n = 0; n < SP.n_subspaces(); ++n) subspaces.emplace_back(n);
        foreach(SP, [this](fock_state_t s, int spn) { subspaces[spn].add_fock_state(s); });

        if(p.verbosity >= 1){
            std::cout << "Found " << subspaces.size() << " invariant subspaces" << std::endl;
            if(p.verbosity >= 2){
                for(int spn = 0; spn < subspaces.size(); ++spn){
                    std::cout << "States in subspace " << spn << ": ";
                    for(auto s : subspaces[spn].get_all_fock_states()) std::cout << s << " ";
                    std::cout << std::endl;
                }
            }
        }
    }

    void distribute_jobs(state<hilbert_space,std::complex<double>,false> const& init_state, params_t const& p) {
        // Jobs distribution
        std::vector<job_t<int>> scheduler_jobs;

        decltype(sub_init_states) all_sub_init_states(subspaces.size());
        scheduler_jobs.reserve(subspaces.size());

        for(int spn = 0; spn < subspaces.size(); ++spn) {
            // Project the initial state on this subspace
            all_sub_init_states[spn] = project<state<sub_hilbert_space, std::complex<double>, false>>(init_state,subspaces[spn]);

            // Any non-zero amplitudes in this subspace?
            bool nontrivial = false;
            foreach(all_sub_init_states[spn],[&nontrivial](int i, std::complex<double> a){
                if(!triqs::utility::is_zero(a)) nontrivial = true;
            });

            if(nontrivial) { // Discard subspaces with trivial evolution
                // Complexity is roughly linear in subspaces[spn].size()
                unsigned int subspace_complexity = subspaces[spn].size();
                scheduler_jobs.push_back({spn,subspace_complexity});
            }
        }

        schedules = lpt_scheduler(scheduler_jobs,comm.size());

        if(p.verbosity >= 2) {
            std::cout << "Distribution of " << scheduler_jobs.size() << " nontrivial subspaces over "
                      << comm.size() << " nodes:" << std::endl;
            for(int nsch = 0; nsch < schedules.size(); ++nsch){
                if(schedules[nsch].empty()){
                    std::cout << "Warning: not enough invariant subspaces to occupy Nodes "
                              << nsch <<  "-" << comm.size()-1 << std::endl;
                    break;
                }
                std::cout << "Node " << nsch << ": ";
                for(auto const& job : schedules[nsch]) std::cout << job.index << " ";
                std::cout << std::endl;
            }
        }

        // Fill sub_init_states
        for(auto const& job : schedules[my_rank])
            sub_init_states.push_back(all_sub_init_states[job.index]);

        // Fill subspace_disp_table
        subspace_disp_table.resize(subspaces.size(),std::make_pair(missing_rank,0));
        for(int nsch = 0; nsch < schedules.size(); ++nsch) {
            int local_id = 0;
            for(auto const& job : schedules[nsch]) {
                subspace_disp_table[job.index] = std::make_pair(nsch,local_id);
                local_id++;
            }
        }
    }

    template<typename Mesh, ode_solve_method Method>
    void run_my_jobs(Mesh const& mesh) {
        if(schedules[my_rank].empty()) return; // Nothing to do on this MPI node

        auto const& my_schedule = schedules[my_rank];

        // Workers to solve the equation
        std::vector<schroedinger_worker<ComplexOperators,Mesh,Method>> workers;
        workers.reserve(my_schedule.size());

        for(auto const& job : my_schedule){
            auto local_id = subspace_disp_table[job.index].second;
            workers.emplace_back(hamiltonian,sub_init_states[local_id],mesh,hbar,stored_psi_values);
        }

        for(bool done = false; !done;) {
            for(auto & worker : workers) {
                done = worker();
            }
            // TODO: Measure observables
        }
    }
};

}