#pragma once

#include <string>
#include <vector>
#include <map>
#include <algorithm>
#include <boost/variant/static_visitor.hpp>
#include <boost/mpi/communicator.hpp>
#include <boost/mpi/collectives.hpp>

#include <triqs/mpi/base.hpp>

#include "common.hpp"
#include "any_mesh.hpp"
#include "mesh_container.hpp"
#include "lpt_scheduler.hpp"
#include "schroedinger_worker.hpp"
#include "observables_worker.hpp"

using triqs::hilbert_space::project;
using triqs::hilbert_space::fock_state_t;

namespace realevol {

using var_results_t = std::map<std::string,any_mesh_container_t<double>>;

struct remote_index_t {
    int rank;
    int local_index;
};

template<bool ComplexOp>
class simulation : public boost::static_visitor<var_results_t> {

    fundamental_operator_set fops;
    space_partition_t<ComplexOp> SP;
    std::vector<sub_hilbert_space> subspaces;
    std::vector<state_on_subspace_t> sub_init_states;
    op_on_subspace_t<ComplexOp> hamiltonian;
    double hbar;
    ode_solve_method method;
    long stored_psi_values;
    std::map<std::string,operator_t<ComplexOp>> observables;

    // MPI data structures
    boost::mpi::communicator & comm;
    std::vector<schedule_t<int>> schedules;
    std::vector<remote_index_t> subspace_disp_table;  // subspace -> remote_index

    template<bool,typename> friend class observables_worker;

public:

    using params_t = solve_parameters_t<ComplexOp>;

    simulation(boost::mpi::communicator & comm,
               fundamental_operator_set const& fops,
               hilbert_space const& hs,
               state<hilbert_space,dcomplex,false> const& init_state,
               params_t const& p
              ) :
        comm(comm),
        fops(fops),
        hamiltonian(p.h,fops), hbar(p.hbar),
        SP({hs},{p.h,fops}),
        method(p.method), stored_psi_values(p.stored_psi_values),
        observables(p.observables)
    {
        if(p.verbosity >= 1){
            std::cout << "Hilbert space is generated by " << fops.size() << " C/C^+ pairs:" << std::endl;
            for(auto const& op : fops){
                for(auto const& i : op.index) std::cout << i << " ";
                std::cout << std::endl;
            }
        }

        // Fill subspaces
        for (int n = 0; n < SP.n_subspaces(); ++n) subspaces.emplace_back(n);
        foreach(SP, [this](fock_state_t s, int spn) { subspaces[spn].add_fock_state(s); });

        if(p.verbosity >= 1){
            std::cout << "Found " << subspaces.size() << " invariant subspaces" << std::endl;
            if(p.verbosity >= 2){
                for(int spn = 0; spn < subspaces.size(); ++spn){
                    std::cout << "States in subspace " << spn << ": ";
                    for(auto s : subspaces[spn].get_all_fock_states()) std::cout << s << " ";
                    std::cout << std::endl;
                }
            }
        }

        distribute_jobs(init_state,p);
    }

    template<typename Mesh> var_results_t operator()(Mesh const& m) {

        results_t<Mesh> results;

        if(schedules[comm.rank()].empty()) { // Nothing to do on this MPI node
            for(auto const& obs : observables) results.emplace(obs.first,typename results_t<Mesh>::mapped_type(m,.0));
        } else {
            stored_psi_values = std::min(stored_psi_values,m.size());

            switch(method) {
                case method_runge_kutta:
                    results = run_my_jobs<Mesh,method_runge_kutta>(m);
                    break;
                case method_lanczos:
                    results = run_my_jobs<Mesh,method_lanczos>(m);
                    break;
                default:
                    TRIQS_RUNTIME_ERROR << "Unknown method to solve the Schroedinger equation: " << method;
            }
        }

        comm.barrier();

        // Sum results over all MPI processes
        var_results_t variant_results;
        for(auto & r : results){
            triqs::mpi::all_reduce_in_place(r.second,comm);
            variant_results.emplace(r);
        }
        return variant_results;
    }

private:

    void distribute_jobs(state_on_space_t const& init_state, params_t const& p) {
        // Jobs distribution
        std::vector<job_t<int>> scheduler_jobs;

        decltype(sub_init_states) all_sub_init_states(subspaces.size());
        scheduler_jobs.reserve(subspaces.size());

        for(int spn = 0; spn < subspaces.size(); ++spn) {
            // Project the initial state on this subspace
            all_sub_init_states[spn] = project<state<sub_hilbert_space, dcomplex, false>>(init_state,subspaces[spn]);

            // Any non-zero amplitudes in this subspace?
            bool nontrivial = false;
            foreach(all_sub_init_states[spn],[&nontrivial](int i, dcomplex a){
                if(!triqs::utility::is_zero(a)) nontrivial = true;
            });

            if(nontrivial) { // Discard subspaces with trivial evolution
                // Complexity is roughly linear in subspaces[spn].size()
                unsigned int subspace_complexity = subspaces[spn].size();
                scheduler_jobs.push_back({spn,subspace_complexity});
            }
        }

        schedules = lpt_scheduler(scheduler_jobs,comm.size());

        if(p.verbosity >= 2) {
            std::cout << "Distribution of " << scheduler_jobs.size() << " nontrivial subspaces over "
                      << comm.size() << " nodes:" << std::endl;
            for(int nsch = 0; nsch < schedules.size(); ++nsch){
                if(schedules[nsch].empty()){
                    std::cout << "Warning: not enough invariant subspaces to occupy Nodes "
                              << nsch <<  "-" << comm.size()-1 << std::endl;
                    break;
                }
                std::cout << "Node " << nsch << ": ";
                for(auto const& job : schedules[nsch]) std::cout << job.index << " ";
                std::cout << std::endl;
            }
        }

        // Fill sub_init_states
        for(auto const& job : schedules[comm.rank()])
            sub_init_states.push_back(all_sub_init_states[job.index]);

        // Fill subspace_disp_table
        subspace_disp_table.resize(subspaces.size(),{-1,0});
        for(int nsch = 0; nsch < schedules.size(); ++nsch) {
            int local_index = 0;
            for(auto const& job : schedules[nsch]) {
                subspace_disp_table[job.index] = {nsch,local_index};
                local_index++;
            }
        }
    }

    template<typename Mesh, ode_solve_method Method>
    results_t<Mesh> run_my_jobs(Mesh const& mesh) {

        auto const& my_schedule = schedules[comm.rank()];

        // Workers to solve the equation
        std::vector<schroedinger_worker<ComplexOp,Mesh,Method>> workers;
        workers.reserve(my_schedule.size());
        // Container with partial solutions:
        std::vector<mesh_container_cyclic<state_on_subspace_t,Mesh>> solution_parts;
        solution_parts.reserve(my_schedule.size());

        observables_worker<ComplexOp,Mesh> obs_worker(mesh,observables,solution_parts,*this);

        for(auto const& job : my_schedule){
            solution_parts.emplace_back(mesh,stored_psi_values);
            solution_parts.back()[0] = sub_init_states.back();

            workers.emplace_back(hamiltonian,solution_parts.back(),hbar);
        }

        for(bool done = false; !done;) {
            for(auto & worker : workers) {
                done = worker();
            }
            obs_worker(stored_psi_values);
        }

        return std::move(obs_worker.get_results());
    }
};

}