#include <triqs/utility/first_include.hpp>

#include <boost/timer/timer.hpp>
#include <boost/variant/static_visitor.hpp>
#include <boost/variant/apply_visitor.hpp>

#include <triqs/draft/hilbert_space_tools/imperative_operator.hpp>

#include "solver.hpp"
#include "space_partition.hpp"
#include "simulation.hpp"

namespace realevol {

using triqs::utility::imperative_operator;
using triqs::utility::sub_hilbert_space;
using triqs::utility::fock_state_t;

template<bool ComplexOperators>
solver<ComplexOperators>::solver(std::set<indices_t> const& operator_indices) :
    fops(operator_indices), hs(fops), init_state(hs)
{
}

template<typename SolverType>
struct solve_visitor : public boost::static_visitor<results_t> {

    SolverType const& S;
    solve_parameters_t<typename SolverType::operator_t> const& p;

    solve_visitor(SolverType const& S, solve_parameters_t<typename SolverType::operator_t> const& p) :
        S(S), p(p) {}

    // Constructs and runs simulations for different time mesh types
    template<typename Mesh>
    results_t operator()(Mesh const& m) {

        if(p.verbosity >= 1){
            std::cout << "Hilbert space is generated by " << S.fops.size() << " C/C^+ pairs:" << std::endl;
            for(auto const& op : S.fops){
                for(auto const& i : op.index) std::cout << i << " ";
                std::cout << std::endl;
            }
        }

        imperative_operator<hilbert_space,typename SolverType::operator_coeff_t,false> hamiltonian(p.h, S.fops);
        state<hilbert_space,typename SolverType::operator_coeff_t,true> st(S.hs);

        // Split the Hilbert space
        space_partition<decltype(st),decltype(hamiltonian)> SP(st, hamiltonian);

        // Fill subspaces
        std::vector<sub_hilbert_space> subspaces;
        for (int n = 0; n < SP.n_subspaces(); ++n) subspaces.emplace_back(n);
        foreach(SP, [&subspaces](fock_state_t s, int spn) { subspaces[spn].add_fock_state(s); });

        if(p.verbosity >= 1){
            std::cout << "Found " << subspaces.size() << " invariant subspaces" << std::endl;
            if(p.verbosity >= 2){
                for(int spn = 0; spn < subspaces.size(); ++spn){
                    std::cout << "States in subspace " << spn << ": ";
                    for(auto s : subspaces[spn].get_all_fock_states()) std::cout << s << " ";
                    std::cout << std::endl;
                }
            }
        }

        simulation<typename SolverType::operator_t,Mesh> sim;

        // TODO

        results_t variant_results;
        for(auto const& r : sim.get_results()) variant_results.emplace(r);

        return variant_results;
    }
};

template<bool ComplexOperators>
void solver<ComplexOperators>::solve(solve_parameters_t<operator_t> const& p) {

    _last_solve_parameters.reset(new solve_parameters_t<operator_t>(p));

    boost::timer::auto_cpu_timer solve_timer(p.verbosity >= 1 ? "Simulation took %w seconds\n" : "");

    auto sv = solve_visitor<solver<ComplexOperators>>(*this,p);
    results = boost::apply_visitor(sv, p.mesh);
}

// Explicit instantiations
template class solver<false>;
template class solver<true>;

}