#include "solver.hpp"

#include <triqs/draft/hilbert_space_tools/imperative_operator.hpp>

#include "space_partition.hpp"
#include "schroedinger_worker.hpp"

namespace realevol {

#define SOLVER_METHOD(RETTYPE,NAME)    template<bool ComplexOperators> RETTYPE solver<ComplexOperators>::NAME
#define AT_VERBOSITY(V)                if(p.verbosity >= V)

SOLVER_METHOD(,solver(std::set<std::string> const& operator_indices)) :
    fops(operator_indices), hs(fops), init_state(hs)
{
}

SOLVER_METHOD(void,solve(solve_parameters_t<operator_t> const& p)){
    AT_VERBOSITY(1){
        std::cout << "Hilbert space is generated by " << fops.size() << " C/C^+ pairs:" << std::endl;
        for(auto const& op : fops){
            for(auto const& i : op.index) std::cout << i << '\t';
            std::cout << std::endl;
        }
    }

    imperative_operator<hilbert_space,operator_coeff_t,false> hamiltonian(p.h, fops);
    state<hilbert_space,operator_coeff_t,true> st(hs);

    // Split the Hilbert space
    space_partition<decltype(st),decltype(hamiltonian)> SP(st, hamiltonian);

    // Fill subspaces
    std::vector<sub_hilbert_space> subspaces;
    for (int n = 0; n < SP.n_subspaces(); ++n) subspaces.emplace_back(n);
    foreach(SP, [&subspaces](fock_state_t s, int spn) { subspaces[spn].add_fock_state(s); });

    AT_VERBOSITY(1){
        std::cout << "Found " << subspaces.size() << " invariant subspaces" << std::endl;
        AT_VERBOSITY(2){
            for(int spn = 0; spn < subspaces.size(); ++spn){
                std::cout << "States in subspace " << spn << ": ";
                for(auto s : subspaces[spn].get_all_fock_states()) std::cout << s << " ";
                std::cout << std::endl;
            }
        }
    }

    // Construct workers to solve Schroedinger equation
//     for(auto sp : subspaces) {
//         schroedinger_worker<> worker();
//     }

}

SOLVER_METHOD(void,help()) {
// TODO
}

#undef SOLVER_METHOD

// Explicit instantiations
template class solver<false>;
template class solver<true>;

}