/*******************************************************************************
 *
 * TRIQS: a Toolbox for Research in Interacting Quantum Systems
 *
 * Copyright (C) 2013-2020, P. Seth, I. Krivenko, M. Ferrero and O. Parcollet
 *
 * TRIQS is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * TRIQS is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * TRIQS. If not, see <http://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
#pragma once

#include <vector>
#include <utility>
#include <algorithm>
#include <cmath>

#include "./fundamental_operator_set.hpp"
#include "../operators/many_body_operator.hpp"
#include "./hilbert_space.hpp"

namespace realevol {
namespace hilbert_space {

/*
   If UseMap is false, the constructor takes two arguments:

   imperative_operator(many_body_op, fundamental_ops)

   a trivial identity connection map is then used.

   If UseMap is true, the constructor takes three arguments:

   imperative_operator(many_body_op, fundamental_ops, hilbert_map)
   */

/// This class is the imperative version of the [[many_body_operator]]
/**
  It is created from a `many_body_operator` object, and is used to act on a [[state]].
  There is an optimization option `UseMap` (useful when `HilbertType = sub_hilbert_space`),
  which allows the user to give a map describing the connections between Hilbert subspaces generated by this operator.
  @warning `HilbertType = sub_hilbert_space` implies that the operator generates only one-to-one connections between the used subspaces. If this not the case, one has to use `HilbertType = hilbert_space`.
  @tparam HilbertType Hilbert space type, one of [[hilbert_space]] and [[sub_hilbert_space]]
  @tparam ScalarType Type of operator's coefficients, normally `double` or `std::complex<double>`
  @tparam UseMap Use a user-provided connection map on construction
  @include triqs/hilbert_space/imperative_operator.hpp
 */
template <typename HilbertType, typename ScalarType = double, bool UseMap = false> class imperative_operator {

 // Fock state convention:
 // |0,...,k> = C^+_0 ... C^+_k |0>
 // Operator monomial convention:
 // C^+_0 ... C^+_i ... C_j  ... C_0

 using scalar_t = ScalarType;

 struct one_term_t {
  scalar_t coeff;
  // Fermions
  uint64_t f_c_mask, f_c_dag_mask, f_c_count_mask, f_c_dag_count_mask;

  // Bosons
  struct single_boson_update_t {
   // Position of the bosonic mode being updated in the fundamental operator set
   int pos;
   // One bosonic subspace is selected as (f >> shift) & mask
   int shift;
   uint64_t mask;
   // Change the number of particles by this number
   int64_t n_change;
   // n_change * (int64_t(1) << shift)
   int64_t state_change;
  };
  std::vector<single_boson_update_t> b_updates;
 };
 std::vector<one_term_t> all_terms;

 std::vector<sub_hilbert_space> const *sub_spaces;
 using hilbert_map_t = std::vector<int>;
 hilbert_map_t hilbert_map;

 std::vector<double> sqr_roots;     // Precomputed square roots of integers
 std::vector<uint64_t> boson_n_max; // Precomputed maximal filling numbers for bosons

 public:

 /// Construct a zero operator
 imperative_operator() {}

 /// Constructor from a `many_body_operator` and a `fundamental_operator_set`
 /**
   @param op Source `many_body_operator` object
   @param fops [[fundamental_operator_set]]; must contain all index sequences met in `op`
   @param full_hs Full Hilbert space the operator is acting on
   @param hmap Map of subspaces-to-subspaces connections generated by `op` (only for `UseMap = true`)
   @param sub_spaces_set Pointer to a vector of all Hilbert subspaces referred by `hmap` (only for `UseMap = true`)
  */
 imperative_operator(operators::many_body_operator_generic<scalar_t> const &op,
                     fundamental_operator_set const &fops,
                     hilbert_space const& full_hs = {},
                     hilbert_map_t hmap = hilbert_map_t(), std::vector<sub_hilbert_space> const *sub_spaces_set = nullptr) {

  auto const& boson_offsets = full_hs.boson_offsets();
  auto const& bits_per_boson = full_hs.bits_per_boson();

  if(fops.size(Boson) != boson_offsets.size())
   TRIQS_RUNTIME_ERROR << "Structure of the bosonic subspace of full_hs is inconsistent with fops";


  sub_spaces = sub_spaces_set;
  hilbert_map = hmap;
  if ((hilbert_map.size() == 0) != !UseMap) TRIQS_RUNTIME_ERROR << "Internal error";

  if(!op.is_zero() && !bits_per_boson.empty()) {
   // Precompute square roots
   int n_sqr_roots = uint64_t(1) << *std::max_element(bits_per_boson.begin(), bits_per_boson.end());
   for(int i = 0; i < n_sqr_roots; ++i) sqr_roots.push_back(std::sqrt(double(i)));

   // Precompute maximal filling numbers for bosons
   boson_n_max.reserve(bits_per_boson.size());
   for(int l : bits_per_boson) boson_n_max.push_back((uint64_t(1) << l) - 1);
  }

  // The goal here is to have a transcription of the many_body_operator in terms
  // of simple vectors (maybe the code below could be more elegant)
  for (auto const &term : op) {
   auto it = std::begin(term.monomial), end_it = std::end(term.monomial);

   // Fermions
   std::vector<int> dag, ndag;
   uint64_t f_c_mask = 0, f_c_dag_mask = 0;
   for (; it != end_it && it->stat != Boson; ++it) {
    (it->dagger ? dag : ndag).push_back(fops.pos(it->indices, Fermion));
    (it->dagger ? f_c_dag_mask : f_c_mask) |= (uint64_t(1) << fops.pos(it->indices, Fermion));
   }
   auto compute_count_mask = [](std::vector<int> const &d) {
    uint64_t mask = 0;
    bool is_on = (d.size() % 2 == 1);
    for (int i = 0; i < 64; ++i) {
     if (std::find(begin(d), end(d), i) != end(d))
      is_on = !is_on;
     else if (is_on)
      mask |= (uint64_t(1) << i);
    }
    return mask;
   };
   uint64_t f_c_count_mask = compute_count_mask(ndag), f_c_dag_count_mask = compute_count_mask(dag);

   // Bosons
   std::vector<typename one_term_t::single_boson_update_t> b_updates;

   auto next_it = it; ++next_it;
   int power = 1;
   for(;it != end_it; ++it, ++next_it) {
    if(next_it == end_it || *next_it != *it) {
     int p = fops.pos(it->indices, Boson);

     // Application of this monomial would inevitably give 0. Skipping.
     if(power > boson_n_max[p]) return;

     int64_t n_change = it->dagger ? power : -power;
     int64_t state_change = n_change * (int64_t(1) << boson_offsets[p]);
     b_updates.push_back({p, boson_offsets[p], (uint64_t(1) << bits_per_boson[p]) - 1, n_change, state_change});

     power = 1;
    } else
     ++power;
   }

   all_terms.push_back(
    one_term_t{scalar_t(term.coef),f_c_mask,f_c_dag_mask,f_c_count_mask,f_c_dag_count_mask,b_updates}
   );
  }
 }

 /// Apply a callable object to each coefficient of the operator by reference
 /**
   The callable object must take one argument convertible to `ScalarType &`

   @tparam Lambda Type of the callable object
   @param L Callable object
  */
 template<typename Lambda> void update_coeffs(Lambda L) {
  for(auto & M : all_terms) L(M.coeff);
 }

 private:

 template <typename StateType>
 inline int get_target_hilbert(StateType const &st, std::true_type /* use_map */) const {
  return hilbert_map[st.get_hilbert().get_index()];
 }
 template <typename StateType>
 inline int get_target_hilbert(StateType const &st, std::false_type /* use_map */) const {
  return st.get_hilbert().get_index();
 }

 template <typename StateType> StateType get_target_st(StateType const &st, std::true_type /* use_map */) const {
  auto n = hilbert_map[st.get_hilbert().get_index()];
  if (n == -1) return StateType{};
  return StateType{(*sub_spaces)[n]};
 }
 template <typename StateType> StateType get_target_st(StateType const &st, std::false_type /* use_map */) const {
  return StateType(st.get_hilbert());
 }

 static bool parity_number_of_bits(uint64_t v) {
  // http://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetNaive
  v ^= v >> 16;
  v ^= v >> 8;
  v ^= v >> 4;
  v ^= v >> 2;
  v ^= v >> 1;
  return v & 0x01;
 }

 // Forward the call to the coefficient
 template<typename... Args>
 static auto apply_if_possible(scalar_t const& x, Args&&... args) { return x(std::forward<Args>(args)...); }
 static auto apply_if_possible(scalar_t const& x) { return x; }

 template <typename StateType, typename... Args>
 inline void apply_impl(StateType const &st, StateType & target_st, Args&&... args) const {
  auto const& hs = st.get_hilbert();
  auto const& target_hs = target_st.get_hilbert();

  for (int i = 0; i < all_terms.size(); ++i) { // loop over monomials
   auto M = all_terms[i];
   foreach(st, [this, M, &target_st, &hs, &target_hs, args...](int i, typename StateType::value_type amplitude) {
    fock_state_t f2 = hs.get_fock_state(i);

    // Fermions
    if ((f2 & M.f_c_mask) != M.f_c_mask) return;
    f2 &= ~M.f_c_mask;
    if (((f2 ^ M.f_c_dag_mask) & M.f_c_dag_mask) != M.f_c_dag_mask) return;
    fock_state_t f3 = ~(~f2 & ~M.f_c_dag_mask);
    auto sign_is_minus = parity_number_of_bits((f2 & M.f_c_count_mask) ^ (f3 & M.f_c_dag_count_mask));

    double coeff = (sign_is_minus ? -1.0 : 1.0);

    // Bosons
    for(int b = M.b_updates.size()-1; b >= 0; --b) {
     auto const& b_update = M.b_updates[b];
     int64_t n_part = (f3 >> b_update.shift) & b_update.mask;
     int64_t new_n_part = n_part + b_update.n_change;
     if(new_n_part < 0 || new_n_part > boson_n_max[b_update.pos]) return;

     if(b_update.n_change > 0) {
      for(int d = 1; d <= b_update.n_change; ++d) coeff *= sqr_roots[n_part + d];
     } else {
      for(int d = 0; d <= -b_update.n_change-1; ++d) coeff *= sqr_roots[n_part - d];
     }
     f3 += b_update.state_change;
    }

    // update state vector in target Hilbert space
    auto ind = target_hs.get_state_index(f3);
    target_st(ind) += coeff * amplitude * apply_if_possible(M.coeff,args...);
   }); // foreach
  }
 }

 public:

 /// Act on a state and overwrite another state with the result
 /**
   The optional extra arguments `args...` are forwarded to the coefficients of the operator.

   `op(phi,psi,args...);`

   We apply an operator obtained from `op` by replacing its monomial coefficients with values
   returned by `coeff(args...)`. This feature makes sense only for ScalarType being a callable object.

   @tparam StateType Type of the initial and final states
   @tparam Args Types of the optional arguments
   @param st Initial state
   @param target_st Target state
   @param args Optional argument pack passed to each coefficient of the operator
  */
 template <typename StateType, typename... Args>
 void apply(StateType const &st, StateType & target_st, Args&&... args) const {
  target_st.zero();
  apply_impl(st, target_st, args...);
 }

 /// Act on a state and return a new state
 /**
   The optional extra arguments `args...` are forwarded to the coefficients of the operator.

   `auto psi = op(phi,args...);`

   We apply an operator obtained from `op` by replacing its monomial coefficients with values
   returned by `coeff(args...)`. This feature makes sense only for ScalarType being a callable object.

   @tparam StateType Type of the initial state
   @tparam Args Types of the optional arguments
   @param st Initial state
   @param args Optional argument pack passed to each coefficient of the operator
  */
 template <typename StateType, typename... Args>
 StateType operator()(StateType const &st, Args&&... args) const {
  StateType target_st = get_target_st(st, std::integral_constant<bool, UseMap>());
  apply_impl(st, target_st, args...);
  return target_st;
 }
};
}}
